import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="shortcut icon" href="../../assets/favicon.ico" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="WebデザイナーHanako Yamada ポートフォリオ" />
        <meta property="og:url" content="URLが入る" />
        <meta property="og:description" content="Hanako Yamadaのポートフォリオサイトです。" />
        <meta property="og:image" content="../../assets/ogp.png" />
        <meta name="description" content="Hanako Yamadaのポートフォリオサイトです" />
      </Head>
      <div className="wrapper">
        <header className="header">
          <div className="header-inner">
            <h1 className="header-logo">
              <a href=".">Hanako{`'`}s Portfolio</a>
            </h1>
            <nav className="header-nav">
              <ul className="header-nav-list">
                <li className="header-nav-item">
                  <a href="#works">Works</a>
                </li>
                <li className="header-nav-item">
                  <a href="#skill">Skill</a>
                </li>
                <li className="header-nav-item">
                  <a href="#contact">Contact</a>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        <main className="content">
          <div className="main-visual">
            <div className="main-visual-img"></div>
          </div>

          <div className="profile">
            <div className="inner">
              <p className="profile-title">Hanako Yamada</p>
              <p className="profile-text">
                30代前半のWebデザイナーです。
                <br />
                デザイン、コーディング、ライティング、SEOなどWeb領域全般に対応できるのが私の強みです。サイト制作はお客様の夢を叶える仕事だと思っています。夢を持っている方と一緒にお仕事ができたら嬉しいです。
              </p>
            </div>
          </div>

          <section className="works section" id="works">
            <div className="inner">
              <h2 className="title">Works</h2>
              <div className="works-list">
                <a className="works-item" href="works-template.html">
                  <p className="works-img">
                    <img src="img/works-sample-thumb.jpg" alt="" />
                  </p>
                  <p className="works-name">作品名が入る</p>
                  <p className="works-info">Design / Coding(Responsive)</p>
                </a>
                <a className="works-item" href="works-template.html">
                  <p className="works-img">
                    <img src="img/works-dummy-thumb.jpg" alt="" />
                  </p>
                  <p className="works-name">作品名が入る</p>
                  <p className="works-info">Design / Coding(Responsive) / WordPress</p>
                </a>
                <a className="works-item" href="works-template.html">
                  <p className="works-img">
                    <img src="img/works-dummy-thumb.jpg" alt="" />
                  </p>
                  <p className="works-name">作品名が入る</p>
                  <p className="works-info">Design</p>
                </a>
                <a className="works-item" href="works-template.html">
                  <p className="works-img">
                    <img src="img/works-dummy-thumb.jpg" alt="" />
                  </p>
                  <p className="works-name">作品名が入る</p>
                  <p className="works-info">Banner Design</p>
                </a>
                <a className="works-item" href="works-template.html">
                  <p className="works-img">
                    <img src="img/works-dummy-thumb.jpg" alt="" />
                  </p>
                  <p className="works-name">作品名が入る</p>
                  <p className="works-info">Banner Design</p>
                </a>
              </div>
            </div>
          </section>

          <section className="skill section" id="skill">
            <div className="inner">
              <h2 className="title">Skill</h2>
              <div className="skill-list">
                <div className="skill-item">
                  <p className="skill-img">
                    <img src="img/icon_skill.png" alt="" />
                  </p>
                  <div className="skill-body">
                    <h3 className="skill-name">HTML5/CSS3</h3>
                    <p className="skill-text">
                      テキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入ります。
                    </p>
                  </div>
                </div>
                <div className="skill-item">
                  <p className="skill-img">
                    <img src="img/icon_skill.png" alt="" />
                  </p>
                  <div className="skill-body">
                    <h3 className="skill-name">WordPress</h3>
                    <p className="skill-text">
                      テキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入ります。
                    </p>
                  </div>
                </div>
                <div className="skill-item">
                  <p className="skill-img">
                    <img src="img/icon_skill.png" alt="" />
                  </p>
                  <div className="skill-body">
                    <h3 className="skill-name">JavaScript</h3>
                    <p className="skill-text">
                      テキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入ります。
                    </p>
                  </div>
                </div>
                <div className="skill-item">
                  <p className="skill-img">
                    <img src="img/icon_skill.png" alt="" />
                  </p>
                  <div className="skill-body">
                    <h3 className="skill-name">Photoshop</h3>
                    <p className="skill-text">
                      テキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入ります。
                    </p>
                  </div>
                </div>
                <div className="skill-item">
                  <p className="skill-img">
                    <img src="img/icon_skill.png" alt="" />
                  </p>
                  <div className="skill-body">
                    <h3 className="skill-name">Illustrator</h3>
                    <p className="skill-text">
                      テキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入ります。
                    </p>
                  </div>
                </div>
                <div className="skill-item">
                  <p className="skill-img">
                    <img src="img/icon_skill.png" alt="" />
                  </p>
                  <div className="skill-body">
                    <h3 className="skill-name">XD</h3>
                    <p className="skill-text">
                      テキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入りますテキストが入ります。
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="contact section" id="contact">
            <div className="inner">
              <h2 className="title">Contact</h2>
              <p className="lead">
                お問い合わせは、
                <br />
                SNSかメールにてお願いいたします。
              </p>
              <div className="contact-list">
                <a
                  className="contact-item"
                  href="https://twitter.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Twitter
                </a>
                <a
                  className="contact-item"
                  href="https://www.instagram.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Instagram
                </a>
                <span className="contact-item">xxxxxx@gmail.com</span>
              </div>
            </div>
          </section>

          <div className="page-top" id="js-page-top">
            <span className="material-icons-outlined">expand_less</span>
          </div>
        </main>

        <footer className="footer">
          <div className="copyright">&copy;Hanako Yamada</div>
        </footer>
      </div>
    </>
  )
}

export default Home
